import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceRoot = path.resolve(packageDir, '..', '..');
const packageAssetsRoot = path.join(packageDir, 'assets');
const generatedMarker = path.join(packageDir, '.press-theme-contract-assets-generated');
const files = [
  ['assets/js/press-version.js', 'assets/js/press-version.js'],
  ['assets/js/theme-contract-surface.mjs', 'assets/js/theme-contract-surface.mjs'],
  ['assets/js/theme-package-core.js', 'assets/js/theme-package-core.js'],
  ['assets/js/theme-route-guard.js', 'assets/js/theme-route-guard.js'],
  ['assets/js/vendor/acorn.mjs', 'assets/js/vendor/acorn.mjs'],
  ['assets/js/vendor/acorn-walk.mjs', 'assets/js/vendor/acorn-walk.mjs'],
  ['assets/js/vendor/fflate.browser.js', 'assets/js/vendor/fflate.browser.js']
];

async function exists(file) {
  try {
    await fs.access(file);
    return true;
  } catch {
    return false;
  }
}

if (process.argv.includes('--clean')) {
  if (await exists(generatedMarker)) {
    await fs.rm(packageAssetsRoot, { recursive: true, force: true });
    await fs.rm(generatedMarker, { force: true });
  }
  process.exit(0);
}

if (await exists(path.join(packageDir, 'assets/js/theme-package-core.js'))) {
  process.exit(0);
}

if (!await exists(path.join(sourceRoot, 'assets/js/theme-package-core.js'))) {
  throw new Error('Cannot prepare @ekilyhq/press-theme-contract assets outside a Press source checkout.');
}

for (const [source, target] of files) {
  const sourcePath = path.join(sourceRoot, source);
  const targetPath = path.join(packageDir, target);
  await fs.mkdir(path.dirname(targetPath), { recursive: true });
  await fs.copyFile(sourcePath, targetPath);
}
await fs.writeFile(generatedMarker, 'generated by prepack\n');
